# Generated by Django 5.0.4 on 2024-04-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compnay',
            old_name='Address',
            new_name='address',
        ),
    ]
